In [1]:
from collections import Counter
import math
import pandas as pd

In [2]:
bo_df = pd.read_excel (r'C:\Users\Lara\Desktop\remove_data\database.xlsx')

In [3]:
bo_df

,API,P[psia],dgs,T[oF],Rs[scf/stb],CO2res[%],CO2gas[%],Pb[psia],RGOformacao[scf/stb],Case,...,error 'Standing',error 'Vazquez e Beggs',error 'Glaso s/corr',error 'Glaso parafina',error 'Al-Marhoun',error 'Petrosky e Farshad',error 'Velarde et al.',error 'Al-Shammasi',Min(abs(error)),Unnamed: 29
0,28.59,4991.320059,0.9400,148.46,8.924757,12.49,16.59,4991.320059,1311.876455,1,...,-0.187741,0.003315,-0.149281,-0.143199,-0.028303,-0.079521,-0.072346,-0.067095,0.003315,'Vazquez e Beggs'
1,28.59,4566.052359,0.9400,148.46,8.604733,12.49,16.59,4991.320059,1311.876455,1,...,-0.160927,0.000261,-0.127556,-0.122074,-0.027574,-0.073834,-0.062973,-0.061876,0.000261,'Vazquez e Beggs'
2,28.59,4139.362359,0.9400,148.46,8.321202,12.49,16.59,4991.320059,1311.876455,1,...,-0.137024,-0.001564,-0.106868,-0.101942,-0.026320,-0.067792,-0.054005,-0.056236,0.001564,'Vazquez e Beggs'
3,28.59,3570.442359,0.9400,148.46,7.993317,12.49,16.59,4991.320059,1311.876455,1,...,-0.106985,-0.001002,-0.079105,-0.074871,-0.022377,-0.057678,-0.041038,-0.046630,0.001002,'Vazquez e Beggs'
4,28.59,2859.292359,0.9400,148.46,7.614341,12.49,16.59,4991.320059,1311.876455,1,...,-0.075332,-0.000702,-0.048183,-0.044767,-0.018488,-0.046263,-0.027584,-0.035932,0.000702,'Vazquez e Beggs'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,24.10,1721.452359,0.7722,190.40,6.718833,0.14,0.25,2984.454759,466.393808,135,...,0.000223,0.000573,0.035927,0.036514,-0.006835,0.011260,0.010058,-0.000545,0.000223,Standing'
1136,24.10,1294.762359,0.7722,190.40,6.592508,0.14,0.25,2984.454759,466.393808,135,...,0.008050,0.002809,0.042859,0.043300,-0.003019,0.018288,0.014362,0.005781,0.002809,'Vazquez e Beggs'
1137,24.10,868.072359,0.7722,190.40,6.463936,0.14,0.25,2984.454759,466.393808,135,...,0.014303,0.004236,0.047601,0.047906,0.000931,0.025427,0.017581,0.011232,0.000931,Al-Marhoun'
1138,24.10,441.382359,0.7722,190.40,6.300555,0.14,0.25,2984.454759,466.393808,135,...,0.014618,0.000344,0.045412,0.045585,0.001423,0.029284,0.015392,0.011509,0.000344,'Vazquez e Beggs'
1139,24.10,14.692359,0.7722,190.40,5.913157,0.14,0.25,2984.454759,466.393808,135,...,-0.009958,-0.028921,0.013918,0.013918,-0.005140,0.036110,-0.010553,-0.011184,0.005140,Al-Marhoun'

In [4]:
bo_df.iloc[:-1, :9] #data points

,API,P[psia],dgs,T[oF],Rs[scf/stb],CO2res[%],CO2gas[%],Pb[psia],RGOformacao[scf/stb]
0,28.59,4991.320059,0.9400,148.46,8.924757,12.49,16.59,4991.320059,1311.876455
1,28.59,4566.052359,0.9400,148.46,8.604733,12.49,16.59,4991.320059,1311.876455
2,28.59,4139.362359,0.9400,148.46,8.321202,12.49,16.59,4991.320059,1311.876455
3,28.59,3570.442359,0.9400,148.46,7.993317,12.49,16.59,4991.320059,1311.876455
4,28.59,2859.292359,0.9400,148.46,7.614341,12.49,16.59,4991.320059,1311.876455
...,...,...,...,...,...,...,...,...,...
1134,24.10,2148.142359,0.7722,190.40,6.850773,0.14,0.25,2984.454759,466.393808
1135,24.10,1721.452359,0.7722,190.40,6.718833,0.14,0.25,2984.454759,466.393808
1136,24.10,1294.762359,0.7722,190.40,6.592508,0.14,0.25,2984.454759,466.393808
1137,24.10,868.072359,0.7722,190.40,6.463936,0.14,0.25,2984.454759,466.393808
1138,24.10,441.382359,0.7722,190.40,6.300555,0.14,0.25,2984.454759,466.393808

In [5]:
bo_df.iloc[:-1, 29] # labels

0       'Vazquez e Beggs'
1       'Vazquez e Beggs'
2       'Vazquez e Beggs'
3       'Vazquez e Beggs'
4       'Vazquez e Beggs'
              ...
1134    'Vazquez e Beggs'
1135           Standing'
1136    'Vazquez e Beggs'
1137          Al-Marhoun'
1138    'Vazquez e Beggs'
Name: Unnamed: 29, Length: 1139, dtype: object

In [6]:
bo_df.iloc[1, 29]

"'Vazquez e Beggs'"

In [7]:
N = bo_df.shape[0] #number of rows
K = 417 #trial and error
k = 10 #k-fold

In [8]:
def euclidean_distance(point1, point2): 
    sum_squared_distance = 0
    for i in range(len(point1)):
        sum_squared_distance += math.pow(point1[i] - point2[i], 2)
    return math.sqrt(sum_squared_distance)

def mode(labels):
    return Counter(labels).most_common(1)[0][0]

In [9]:
def df_to_tuples(dataframe):
    tuples_list = []
    lists = dataframe.values.tolist()
    for sublist in lists:
        tuples_list.append(tuple(sublist))
    return tuples_list

def knn(data, query, k): # data as list of tuples, query as tuple
    distances_and_indices = []
    
    for index, point in enumerate(data):
        assert len(point) == len(query), "Length mismatch in data points"
        distance = euclidean_distance(point, query)
        distances_and_indices.append((distance, index))


    k_nearest = sorted(distances_and_indices)[:k] #ascending order
    #print("Nearest", k_nearest)
    k_nearest_labels = [bo_df.iloc[i, 29] for distance, i in k_nearest]
    #print("Nearest labels:", k_nearest_labels)
    return mode(k_nearest_labels)

def split(data, k): # for k-fold
    sections = []
    
    for i in range(0, len(data), k):
        sections += data[i:i + k]
        
    return sections

def fold(data, query, k):
    sections = split(data, k)
    tried_sections = []
    results = []
    
    for i, section in enumerate(sections):
        del sections[i]
        new_data = tried_sections + sections
        results.append(knn(new_data, query, K))
        tried_sections.append(section)
        
    #print("Results:", results)
    return mode(results)

In [10]:
queries = [tuple(bo_df.iloc[i, :9].values.tolist()) for i in range(100)]

In [11]:
data = df_to_tuples(bo_df.iloc[101:, :9])

In [12]:
accurate = 0
for i, query in enumerate(queries):
    if fold(data, query, k) == bo_df.iloc[i, 29]:
        accurate += 1
        
accuracy = accurate / len(queries)
accuracy

0.38